import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
const compiled=await build({entryPoints:['web/src/github-publish.ts'],bundle:true,write:false,format:'esm',platform:'node'});
const {submitConfiguration,submissionStatus,mergeSubmission,RemoteChanged,BranchCreated}=await import(`data:text/javascript;base64,${Buffer.from(compiled.outputFiles[0].text).toString('base64')}`);
const base={schema_version:'1.0',repository:{owner:'chcaty',name:'garss-next',branch:'main',path:'sources.json'},sources:[{id:'a',title:'来源',category:'科技',description:'',feed_url:'https://example.com/rss',enabled:true}]};
const draft={...base,sources:[{...base.sources[0],title:'拾阅中文'}]};
const head='a'.repeat(40),calls=[];
const response=value=>new Response(JSON.stringify(value));
const file=value=>({sha:'blob',encoding:'base64',content:Buffer.from(JSON.stringify(value)).toString('base64')});
function fixture(values){const seen=[];return {seen,fetcher:async(url,options)=>{assert.ok(url.startsWith('https://api.github.com/repos/chcaty/garss-next/'));assert.equal(options.redirect,'error');seen.push({url,options});const next=values.shift();if(next instanceof Error)throw next;assert.notEqual(next,undefined,'unexpected request');return response(next);}};}
test('remote edits stop publishing before any writes',async()=>{const mock=fixture([{object:{sha:head}},file({...base,sources:[]})]);await assert.rejects(submitConfiguration(base,draft,'test-token',mock.fetcher),RemoteChanged);assert.ok(mock.seen.every(call=>call.options.method==='GET'));});
test('publishing preserves Unicode and stores the token only in GitHub authorization headers',async()=>{const mock=fixture([{object:{sha:head}},file(base),{}, {commit:{sha:head}}, {html_url:'https://github.com/chcaty/garss-next/pull/2',number:2}]);const result=await submitConfiguration(base,draft,'test-token',mock.fetcher);assert.equal(result.head,head);assert.equal(result.number,2);const put=mock.seen.find(call=>call.options.method==='PUT');assert.deepEqual(JSON.parse(Buffer.from(JSON.parse(put.options.body).content,'base64').toString()),draft);assert.ok(mock.seen.every(call=>call.options.headers.Authorization==='Bearer test-token'));assert.ok(mock.seen.every(call=>!call.url.includes('test-token')&&!call.options.body?.includes('test-token')));});
test('PR failures keep a reviewable configuration branch',async()=>{const mock=fixture([{object:{sha:head}},file(base),{}, {commit:{sha:head}},new Error('network')]);await assert.rejects(submitConfiguration(base,draft,'test-token',mock.fetcher),error=>error instanceof BranchCreated&&error.url.startsWith('https://github.com/chcaty/garss-next/compare/main...sources/'));assert.equal(mock.seen.filter(call=>call.options.method==='DELETE').length,0);});
const submission={number:2,branch:'sources/2026-10-03-test',head,url:'https://github.com/chcaty/garss-next/pull/2',fingerprint:''};
const pull={base:{ref:'main',repo:{full_name:'chcaty/garss-next'}},head:{ref:submission.branch,sha:head},state:'open',merged:false,mergeable:true,mergeable_state:'clean'};
test('unfinished checks and changed PR heads cannot merge',async()=>{const waiting=fixture([pull,{check_runs:[{name:'check',app:{slug:'github-actions'},status:'in_progress'}]}]);await assert.rejects(mergeSubmission(base,submission,'test-token',waiting.fetcher),/等待/);assert.ok(waiting.seen.every(call=>call.options.method==='GET'));const changed=fixture([{...pull,head:{...pull.head,sha:'b'.repeat(40)}}]);await assert.rejects(mergeSubmission(base,submission,'test-token',changed.fetcher),/已变化/);assert.equal(changed.seen.length,1);});
test('merging rechecks validation and pins the reviewed commit',async()=>{const mock=fixture([pull,{check_runs:[{name:'check',app:{slug:'github-actions'},status:'completed',conclusion:'success',started_at:'2026-10-03T00:00:00Z'}]},{merged:true}]);await mergeSubmission(base,submission,'test-token',mock.fetcher);assert.deepEqual(JSON.parse(mock.seen.at(-1).options.body),{sha:head,merge_method:'squash'});assert.equal(mock.seen[1].options.headers.Authorization,undefined);});
