import {useState} from 'react';
import {type Source,webUrl} from './catalog.ts';
export interface Directory {url:string;page:string;category:string;name?:string;updated_at?:string;update_evidence?:string;maintenance_checked_at?:string;status?:string;checked_at?:string;feed_count?:number;error?:string;}
const date=(value?:string)=>value?new Date(value).toLocaleDateString('zh-CN',{timeZone:'Asia/Shanghai'}):'未核对';
export function Provenance({directories,states,candidates,onCandidates,known=true}:{known?:boolean;directories:Directory[];states:Directory[];candidates:Source[];onCandidates:(page:string)=>void}) {
 const [query,setQuery]=useState(''),[recentOnly,setRecentOnly]=useState(false);
 const groups=new Map<string,Directory[]>();for(const item of directories){const group=groups.get(item.page)??[];group.push({...item,...states.find(state=>state.url===item.url)});groups.set(item.page,group);}
 const threshold=new Date();threshold.setMonth(threshold.getMonth()-3);
 const providers=[...groups].map(([page,files])=>({page,files,name:files[0].name??new URL(page).pathname.slice(1),updated:files.map(item=>item.updated_at).filter((value):value is string=>!!value).sort().at(-1),count:candidates.filter(item=>item.discovered_from===page).length}));
 const recent=providers.filter(item=>!!item.updated&&new Date(item.updated)>=threshold);
 const list=providers.filter(item=>(!recentOnly||recent.includes(item))&&`${item.name} ${item.page} ${item.files.map(file=>file.category).join(' ')}`.toLowerCase().includes(query.toLowerCase()));
 return <section className="py-6" aria-label="发现出处目录"><h2 className="text-xl font-semibold">这些 RSS 从哪里发现</h2><p className="mt-3 text-sm leading-7 text-muted">按独立项目计数，同一出处的多个分类只计一次。目录可读取后，RSS 地址仍需逐个验证，通过后才进入候选。</p><p className="mt-3 text-sm font-medium">{providers.length} 个独立出处 · {recent.length} 个清单近三个月有更新</p><div className="my-5 flex flex-wrap items-center gap-4"><label className="min-w-0 flex-1"><span className="sr-only">搜索出处</span><input className="field" placeholder="搜索项目、分类或出处网址" type="search" value={query} onChange={event=>setQuery(event.target.value)}/></label><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={recentOnly} onChange={event=>setRecentOnly(event.target.checked)}/>近三个月有更新</label></div><div className="border-t border-line">{list.map(item=>{const checked=item.files.map(file=>file.checked_at).filter(Boolean).sort().at(-1),failed=item.files.filter(file=>file.status==='error');return <article key={item.page} className="border-b border-line py-5"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0"><h3 className="break-words font-semibold">{item.name}</h3><p className="mt-2 text-xs leading-6 text-muted">{[...new Set(item.files.map(file=>file.category))].join(' · ')}</p><p className="mt-2 text-xs leading-6 text-muted">清单更新 {date(item.updated)} · 维护证据核对 {date(item.files[0].maintenance_checked_at)}</p><p className="mt-1 text-xs leading-6 text-muted">最近目录检查 {date(checked)} · {checked?failed.length?`${failed.length} 个目录异常`:'目录可读取':known?'等待新版检查':'检查状态未知'} · {known?item.count:'—'} 个待确认来源</p></div><button className="btn" disabled={!known||!item.count} onClick={()=>onCandidates(item.page)}>查看候选</button></div><div className="mt-3 flex flex-wrap gap-5 text-xs text-brand">{webUrl(item.page)?<a href={item.page} target="_blank" rel="noopener noreferrer" className="underline underline-offset-4">打开出处</a>:null}{item.files.find(file=>file.update_evidence)&&webUrl(item.files.find(file=>file.update_evidence)!.update_evidence!)?<a href={item.files.find(file=>file.update_evidence)!.update_evidence} target="_blank" rel="noopener noreferrer" className="underline underline-offset-4">查看更新证据</a>:null}<details className="text-muted"><summary className="cursor-pointer">目录文件 {item.files.length}</summary><ul className="mt-3 space-y-3">{item.files.map(file=><li key={file.url}>{webUrl(file.url)?<a href={file.url} target="_blank" rel="noopener noreferrer" className="break-all underline underline-offset-4">{file.category} · 下载 OPML</a>:file.category}{file.error?<p className="mt-1 break-words text-red-800">{file.error}</p>:null}</li>)}</ul></details></div></article>;})}{!list.length?<p className="py-10 text-sm text-muted">没有匹配的出处。清除关键词或更新筛选后重试。</p>:null}</div></section>;
}
