import {useEffect,useRef,useState} from 'react';
import {type SourceConfig} from './catalog.ts';
import {BranchCreated,RemoteChanged,fingerprint,submitConfiguration,submissionStatus,mergeSubmission,type Submission} from './github-publish.ts';
export function Publisher({base,draft,blocked,onConflict}:{base:SourceConfig;draft:SourceConfig;blocked:boolean;onConflict:(value:SourceConfig)=>void}){
 const key=`shiyue-submission:${base.repository.owner}/${base.repository.name}`;
 const [submission,setSubmission]=useState<Submission|undefined>(()=>{try{const value=JSON.parse(localStorage.getItem(key)??'null');return value&&Number.isSafeInteger(value.number)&&/^sources\/[\w-]+$/.test(value.branch)&&/^[a-f0-9]{40}$/.test(value.head)&&typeof value.fingerprint==='string'?value:undefined;}catch{return undefined;}});
 const token=useRef<HTMLInputElement>(null),[hasToken,setHasToken]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('草稿不会自动采集。先提交 PR，通过校验并合并后才会生效。'),[ready,setReady]=useState(false),[merged,setMerged]=useState(false),[branchUrl,setBranchUrl]=useState('');
 useEffect(()=>()=>{if(token.current)token.current.value='';},[]);
 const identical=submission?.fingerprint===fingerprint(draft);
 async function action(kind:'submit'|'refresh'|'merge'){
  if(!token.current?.value||busy)return;setBusy(true);setReady(false);setMessage(kind==='submit'?'正在核对远程配置并创建分支…':kind==='merge'?'重新检查校验结果并合并…':'正在读取 PR 状态…');
  try{
   if(kind==='submit'){const next=await submitConfiguration(base,draft,token.current.value);setSubmission(next);try{localStorage.setItem(key,JSON.stringify(next));}catch{}setMessage('PR 已创建，等待校验。请刷新状态后合并。');}
   else if(submission){if(kind==='merge'){if(!identical||blocked)throw Error('草稿已变化，请重新检查；此 PR 保留已提交的版本。');await mergeSubmission(base,submission,token.current.value);setMerged(true);setMessage('已合并，等待 CI 采集和发布。可在同步记录查看进度。');token.current.value='';setHasToken(false);}else{const status=await submissionStatus(base,submission,token.current.value);setReady(status.ready);setMerged(status.merged);setMessage(status.message);}}
  }catch(error){if(error instanceof RemoteChanged)onConflict(error.config);if(error instanceof BranchCreated)setBranchUrl(error.url);setMessage(error instanceof Error?error.message:'操作未完成，请在 GitHub 核对状态后再重试。');}finally{setBusy(false);}
 }
 return <section className="mt-5 space-y-4" aria-label="在页面提交"><h3 className="font-semibold">在此页面提交到 GitHub</h3><p className="text-xs leading-6 text-muted">使用仅授权此仓库的 Token，权限为 Contents 和 Pull requests 读写。凭据仅在当前窗口使用，关闭后清除；页面不会保存。<a className="ml-2 text-brand underline" href="https://github.com/settings/personal-access-tokens/new" target="_blank" rel="noopener noreferrer">创建 Token</a></p>{!merged?<label className="block text-sm">GitHub Token<input ref={token} className="field mt-2" type="password" autoComplete="off" spellCheck={false} disabled={busy} onChange={event=>setHasToken(!!event.target.value.trim())}/></label>:null}<p role="status" className="text-sm leading-6 text-muted">{message}</p>{submission?<p className="text-sm"><a className="text-brand underline" href={`https://github.com/${base.repository.owner}/${base.repository.name}/pull/${submission.number}`} target="_blank" rel="noopener noreferrer">查看 PR #{submission.number}</a>{!identical?<span className="ml-2 text-muted">草稿已另有改动，此 PR 保留提交时的配置。</span>:null}</p>:null}{branchUrl?<a className="block text-sm text-brand underline" href={branchUrl} target="_blank" rel="noopener noreferrer">打开配置分支，继续创建 PR</a>:null}<div className="flex flex-wrap gap-2">{!submission?<button className="btn btn-primary" disabled={blocked||!hasToken||busy||!!branchUrl} onClick={()=>void action('submit')}>提交配置并创建 PR</button>:!merged?<><button className="btn" disabled={busy||!hasToken} onClick={()=>void action('refresh')}>刷新校验状态</button><button className="btn btn-primary" disabled={blocked||!identical||!ready||busy||!hasToken} onClick={()=>void action('merge')}>合并并开始采集</button></>:<><a className="btn btn-primary" href="./sync.html">查看同步记录</a><button className="btn" onClick={()=>{setSubmission(undefined);setMerged(false);setReady(false);try{localStorage.removeItem(key);}catch{}setMessage('重新加载发布配置后，可继续提交新的改动。');}}>完成此提交</button></>}</div><p className="text-xs leading-6 text-muted">拥有仓库写入权限才能提交或合并。读者可使用下方复制、下载方式提出来源建议。</p></section>;
}
