import {Publisher} from './publisher.tsx';
import {useEffect, useMemo, useRef, useState, type ReactNode} from 'react';
import {Provenance,type Directory} from './provenance.tsx';
import {Shell} from './shell.tsx';
import {createRoot} from 'react-dom/client';
import {Button, Checkbox, Dialog, DialogBackdrop, DialogPanel, DialogTitle, Description, Field, Label, Input, Textarea, Switch, Listbox, ListboxButton, ListboxOptions, ListboxOption, Menu, MenuButton, MenuItems, MenuItem, TabGroup, TabList, Tab, TabPanels, TabPanel} from '@headlessui/react';
import {readJson, validateConfig, webUrl, type Source, type SourceConfig} from './catalog.ts';
import {changes, duplicateUrls, matchesSource, fieldLabels, fieldValue} from './source-management.ts';
import {archived, rebaseDraft, draftConflicts, importOpml, exportOpml, type Health} from './source-manager-model.ts';

const draftKey = `garss-next-sources:${location.pathname}`;
const pageSize=20;
const emptySource=():Source=>({id:`user-${crypto.randomUUID()}`,title:'',description:'',category:'',feed_url:'',enabled:true});
const formatDate=(value?:string)=>value ? new Date(value).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}) : '暂无记录';
const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:{value:string;label:string}[]}) {
  return <Field className="relative min-w-0"><Label className="mb-2 block text-xs text-muted">{label}</Label><Listbox value={value} onChange={onChange}><ListboxButton className="field flex items-center justify-between text-left"><span className="truncate">{options.find(item=>item.value===value)?.label ?? value}</span><svg aria-hidden="true" viewBox="0 0 20 20" className="ml-2 size-4 shrink-0" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="m6 8 4 4 4-4"/></svg></ListboxButton><ListboxOptions className="absolute z-20 mt-2 max-h-64 w-full overflow-auto rounded-md border border-line bg-panel p-1 shadow-lg">{options.map(item=><ListboxOption key={item.value} value={item.value} className="cursor-pointer rounded px-3 py-3 text-sm data-focus:bg-soft data-selected:font-semibold">{item.label}</ListboxOption>)}</ListboxOptions></Listbox></Field>;
}
function Check({checked,onChange,label}:{checked:boolean;onChange:(value:boolean)=>void;label:string}) {
  return <Checkbox checked={checked} onChange={onChange} aria-label={label} className="group flex size-11 shrink-0 items-center justify-center"><span className="flex size-5 items-center justify-center rounded border border-line bg-panel group-data-checked:border-brand group-data-checked:bg-brand"><svg aria-hidden="true" className={checked?'size-4 text-panel':'invisible size-4'} viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2"><path d="m4 10 4 4 8-8"/></svg></span></Checkbox>;
}
function Modal({open,title,description,onClose,children,wide=false}:{wide?:boolean;open:boolean;title:string;description?:string;onClose:()=>void;children:ReactNode}) {
  return <Dialog open={open} onClose={onClose} className="fixed inset-0 z-50"><DialogBackdrop className="fixed inset-0 bg-ink/35"/><div className="fixed inset-0 overflow-y-auto p-4 sm:p-8"><div className="flex min-h-full items-center justify-center"><DialogPanel className={wide?"review-panel w-full max-w-3xl rounded-xl bg-panel p-6 shadow-xl":"w-full max-w-xl rounded-xl bg-panel p-6 shadow-xl"}><div className="flex items-start justify-between gap-4"><DialogTitle className="text-xl font-semibold">{title}</DialogTitle><Button className="btn" onClick={onClose}>关闭</Button></div>{description ? <Description className="mt-3 text-sm leading-6 text-muted">{description}</Description>:null}{children}</DialogPanel></div></div></Dialog>;
}
function Manager() {
  const [directoryStatus,setDirectoryStatus]=useState('loading');const [stateStatus,setStateStatus]=useState('loading');const [discoveryStatus,setDiscoveryStatus]=useState('loading');
  async function retrySection(section:'states'|'discovery'|'directories'){
    if(section==='states'){setStateStatus('loading');try{const value=await readJson<{sources:Record<string,Health>}>('./api/v1/source-state.json');setHealth(value.sources);setStateStatus('ready');}catch{setStateStatus('error');}}
    else if(section==='directories'){setDirectoryStatus('loading');try{const value=await readJson<{directories:Directory[]}>('./assets/sources/directories.json');setDirectories(value.directories);setDirectoryStatus('ready');}catch{setDirectoryStatus('error');}}
    else{setDiscoveryStatus('loading');try{const value=await readJson<typeof discovery>('./api/v1/source-discovery.json');setDiscovery({...value,candidates:value.candidates??[]});setDiscoveryStatus('ready');}catch{setDiscoveryStatus('error');}}
  }

  const [published,setPublished]=useState<SourceConfig>(); const [config,setConfig]=useState<SourceConfig>(); const [base,setBase]=useState<SourceConfig>();
  const [health,setHealth]=useState<Record<string,Health>>({}); const [feeds,setFeeds]=useState<Map<string,Source>>(new Map());
  const [discovery,setDiscovery]=useState<{candidates:Source[];last_attempt_at?:string;directory_errors?:{directory:string;error:string}[];directories?:Directory[]}>({candidates:[]});
  const [message,setMessage]=useState('正在加载来源配置…'); const [loading,setLoading]=useState(true);const [loadError,setLoadError]=useState(false);
  const [directories,setDirectories]=useState<Directory[]>([]);const [provider,setProvider]=useState('');
  const [stale,setStale]=useState(false); const [tab,setTab]=useState(()=>location.hash==='#provenance'?3:0); const [query,setQuery]=useState(''); const [category,setCategory]=useState('all'); const [filter,setFilter]=useState('all');const [page,setPage]=useState(1);
  const [selected,setSelected]=useState<Set<string>>(new Set()); const [editing,setEditing]=useState<Source>(); const [editorInitial,setEditorInitial]=useState<Source>(); const [editError,setEditError]=useState('');
  const [review,setReview]=useState(false);const [confirmAction,setConfirmAction]=useState<{title:string;description:string;run:()=>void}>();
  const importInput=useRef<HTMLInputElement>(null);
  const dirty=!!editing && !same(editing,editorInitial);
  const diff=useMemo(()=>changes(published?.sources ?? [],config?.sources ?? []),[published,config]);
  const [conflictReviewed,setConflictReviewed]=useState(false);
  const conflicts=useMemo(()=>base&&config&&published?draftConflicts(base,config,published):[],[base,config,published]);
  useEffect(()=>setConflictReviewed(false),[base,config,published]);
  const acceptPublished=(latest:SourceConfig)=>{setPublished(latest);setConfig(latest);setBase(latest);setStale(false);try{localStorage.removeItem(draftKey);}catch{}setMessage('全部改动已在公共目录发布，本机草稿已与发布版本一致。');};
  const modified=useMemo(()=>new Set(diff.map(item=>item.id)),[diff]); const duplicates=useMemo(()=>duplicateUrls(config?.sources ?? []),[config]);
  const save=(next:SourceConfig)=>{validateConfig(next);setConfig(next);try {localStorage.setItem(draftKey,JSON.stringify({version:2,base:base ?? published,config:next}));setMessage('草稿已保存在此浏览器，提交并发布后生效。');} catch {setMessage('浏览器无法保存草稿，请下载 JSON 备份后再离开页面。');}};
  const updateSources=(sources:Source[])=>{if(config)save({...config,sources});};
  useEffect(()=>{if(!dirty)return;const guard=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty]);
  useEffect(()=>{let alive=true;
    async function load(){
      const ancillary=Promise.allSettled([readJson<{sources:Record<string,Health>}>('./api/v1/source-state.json'),readJson<{feeds:Source[]}>('./api/v1/feeds.json'),readJson<typeof discovery>('./api/v1/source-discovery.json'),readJson<{directories:Directory[]}>('./assets/sources/directories.json')]);
      try {const value=await readJson<unknown>('./api/v1/sources.json');validateConfig(value);let draft=value;let baseline=value;let recovered=false;let outdated=false;
        try {const stored=localStorage.getItem(draftKey);if(stored){const saved=JSON.parse(stored);const local=saved.version===2?saved.config:saved;validateConfig(local);if(local.repository.owner===value.repository.owner && local.repository.name===value.repository.name){draft=local;recovered=true;if(saved.version===2){validateConfig(saved.base);baseline=saved.base;outdated=!same(baseline,value) && !same(draft,value);}else {outdated=!same(local,value);const ids=new Set(local.sources.map(source=>source.id));baseline={...value,sources:value.sources.filter(source=>ids.has(source.id))};}}}}catch{if(alive)setMessage('原草稿无法读取，已加载发布配置。');}
        if(same(draft,value)){baseline=value;outdated=false;}
        if(!alive)return;setPublished(value);setConfig(draft);setBase(baseline);setStale(outdated);setLoading(false);setMessage(recovered&&!same(draft,value)?'已恢复本机草稿。尚未提交或发布。':'已加载发布配置。');
        const result=await ancillary;if(!alive)return;const [states,entries,candidates,directoryConfig]=result;
        setDirectoryStatus(directoryConfig.status==='fulfilled'?'ready':'error');setStateStatus(states.status==='fulfilled'?'ready':'error');setDiscoveryStatus(candidates.status==='fulfilled'?'ready':'error');
        if(states.status==='fulfilled')setHealth(states.value.sources ?? {});
        if(entries.status==='fulfilled')setFeeds(new Map(entries.value.feeds.map(item=>[item.id,item])));
        if(directoryConfig.status==='fulfilled')setDirectories(directoryConfig.value.directories);
        if(candidates.status==='fulfilled')setDiscovery({...candidates.value,candidates:candidates.value.candidates ?? []});
        if(result.some(item=>item.status==='rejected'))setMessage('来源配置已加载，部分状态暂未发布或读取失败；可继续编辑，刷新页面可重试。');
      }catch{if(alive){setLoadError(true);setLoading(false);setMessage('来源配置加载失败。请检查网络后重新加载。');}}
    }void load();return()=>{alive=false;};
  },[]);
  const authored=config?.sources ?? [];
  const archive=authored.filter(source=>archived(source,health[source.id]));const active=authored.filter(source=>!archived(source,health[source.id]));
  const candidates=discovery.candidates.filter(source=>!authored.some(item=>item.id===source.id || item.feed_url===source.feed_url));
  const pool=tab===0?active:tab===1?candidates:archive;
  const categories=[...new Set(pool.map(source=>source.category))].sort((a,b)=>a.localeCompare(b,'zh'));
  const list=pool.filter(source=>matchesSource(source,query,category)&&(!provider||tab!==1||source.discovered_from===provider)&&(tab!==0 || filter==='all' || filter==='enabled'&&source.enabled || filter==='disabled'&&!source.enabled || filter==='ok'&&source.enabled&&health[source.id]?.status!=='error'&&feeds.get(source.id)?.status!=='error'&&(health[source.id]?.status==='active'||feeds.get(source.id)?.status==='ok') || filter==='error'&&source.enabled&&(health[source.id]?.status==='error'||feeds.get(source.id)?.status==='error') || filter==='duplicate'&&duplicates.has(source.feed_url) || filter==='changed'&&modified.has(source.id)));
  const pages=Math.max(1,Math.ceil(list.length/pageSize)); const currentPage=Math.min(page,pages); const visible=list.slice((currentPage-1)*pageSize,currentPage*pageSize);
  const download=(name:string,content:string,type:string)=>{const url=URL.createObjectURL(new Blob([content],{type}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  const configText=()=>{if(!config)throw Error('配置尚未加载');validateConfig(config);return JSON.stringify(config,null,2)+'\n';};
  const closeEditor=()=>{if(dirty)setConfirmAction({title:'放弃尚未保存的输入？',description:'已保存的来源草稿会保留，当前编辑面板的输入将被丢弃。',run:()=>setEditing(undefined)});else setEditing(undefined);};
  const openEditor=(source:Source)=>{setEditing({...source});setEditorInitial({...source});setEditError('');};
  const commitEditor=(event:React.FormEvent)=>{event.preventDefault();if(!editing||!config)return;const next={...editing,title:editing.title.trim(),feed_url:editing.feed_url.trim(),category:editing.category.trim(),description:editing.description.trim()};
    if(!next.title||!next.category||!webUrl(next.feed_url)){setEditError('请填写名称和分类，以及有效的 HTTP(S) RSS 地址。');return;}
    const old=authored.find(source=>source.id===next.id);if(next.feed_url!==old?.feed_url&&duplicateUrls([next,...authored.filter(source=>source.id!==next.id)]).has(next.feed_url)){setEditError('这个 RSS 地址已存在，请编辑已有来源。');return;}
    updateSources(old?authored.map(source=>source.id===next.id?next:source):[...authored,next]);setEditing(undefined);setSelected(new Set());};
  const batch=(enabled:boolean)=>{updateSources(authored.map(source=>selected.has(source.id)?{...source,enabled}:source));setSelected(new Set());};
  const restore=(source:Source)=>{updateSources(authored.map(item=>item.id===source.id?{...item,enabled:true,recheck_requested_at:new Date().toISOString()}:item));setMessage('复查请求已加入草稿。提交发布后立即复查，通过后恢复采集。');};
  const reset=()=>setConfirmAction({title:'丢弃全部本机草稿？',description:'新增、编辑、启停和复查请求都会恢复为已发布配置。',run:()=>{if(!published)return;setConfig(structuredClone(published));setBase(published);setStale(false);setSelected(new Set());try{localStorage.removeItem(draftKey);}catch{}setMessage('已恢复已发布配置。');}});
  async function importFile(file?:File){if(!file||!config)return;if(file.size>2_000_000){setMessage('OPML 文件不能超过 2 MB。');return;}try {const sources=importOpml(await file.text(),authored);updateSources([...authored,...sources]);setMessage(`已导入 ${sources.length} 个来源到草稿，尚未发布。`);}catch(error){setMessage(error instanceof Error?error.message:'导入失败，请检查文件。');}if(importInput.current)importInput.current.value='';}
  const panelContent = <>
  {(tab===1&&discoveryStatus!=='ready')||((tab===0||tab===2)&&stateStatus!=='ready')?<div role="status" className="my-4 text-sm text-muted"><p>{(tab===1?discoveryStatus:stateStatus)==='loading'?'正在读取状态…':'状态读取失败，数量未知；已有数据保留。'}</p><Button className="btn mt-2" disabled={(tab===1?discoveryStatus:stateStatus)==='loading'} onClick={()=>void retrySection(tab===1?'discovery':'states')}>重试{tab===1?'发现状态':'来源状态'}</Button></div>:null}
  <p className="mb-6 mt-4 max-w-3xl text-sm leading-6 text-muted">{tab===0?'已启用来源由 CI 定时采集。短暂失败会标记异常，持续失败才会归档。':tab===1?`每 7 天从公开目录发现一批来源，单次最多验证 20 个地址。验证通过后放在这里，由你决定是否加入并提交。最近发现：${formatDate(discovery.last_attempt_at)}`:'连续失败至少 3 次且持续 24 小时后归档，暂停日常采集；每 7 天自动复查，也可以提交立即复查请求。'}</p>
  {tab===1&&discovery.directory_errors?.length?<p className="mb-4 text-sm text-red-800">部分外部目录读取失败，将保留已有候选，并在下次发现时重试。</p>:null}
  <div className="grid grid-cols-2 gap-3 sm:grid-cols-[minmax(0,1fr)_180px_180px]"><Field className="col-span-2 sm:col-span-1"><Label className="mb-2 block text-xs text-muted">搜索来源</Label><Input className="field" type="search" placeholder="名称、RSS 地址或简介" value={query} onChange={event=>{setQuery(event.target.value);setPage(1);}}/></Field><Choice label="分类" value={category} onChange={value=>{setCategory(value);setPage(1);}} options={[{value:'all',label:'全部分类'},...categories.map(value=>({value,label:value}))]}/>{tab===0?<Choice label="筛选" value={filter} onChange={value=>{setFilter(value);setPage(1);}} options={[['all','全部来源'],['enabled','已启用'],['disabled','已停用'],['ok','采集正常'],['error','采集异常'],['duplicate','重复地址'],['changed','草稿有改动']].map(([value,label])=>({value,label}))}/>:null}</div>
  <div className="flex flex-wrap items-center gap-3 py-5 text-xs text-muted">{tab===0?<><Check checked={visible.length>0&&visible.every(source=>selected.has(source.id))} label="选择本页" onChange={checked=>{setSelected(prior=>{const next=new Set(prior);visible.forEach(source=>checked?next.add(source.id):next.delete(source.id));return next;});}}/><span>选择本页</span></>:null}<span>{list.length} 个匹配 / {pool.length} 个来源</span></div>
  {selected.size?<div className="mb-3 flex flex-wrap items-center gap-2 rounded-md bg-soft p-3"><strong className="mr-auto text-sm">已选择 {selected.size} 个来源</strong><Button className="btn" onClick={()=>batch(true)}>启用所选</Button><Button className="btn" onClick={()=>batch(false)}>停用所选</Button><Button className="btn" onClick={()=>setSelected(new Set())}>取消选择</Button></div>:null}
  <div className="border-t border-line">{loading?<p className="py-12 text-center text-muted">正在读取来源…</p>:visible.length?visible.map(source=>{const state=health[source.id],last=feeds.get(source.id);return <article key={source.id} className="flex items-start gap-3 border-b border-line py-5 sm:gap-5">{tab===0?<div className="pt-1"><Check checked={selected.has(source.id)} label={`选择 ${source.title} (${source.id})`} onChange={checked=>setSelected(prior=>{const next=new Set(prior);checked?next.add(source.id):next.delete(source.id);return next;})}/></div>:null}<div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="break-words text-base font-semibold">{source.title}</h2>{modified.has(source.id)?<span className="pill">草稿改动</span>:null}</div><p className="mt-1 truncate text-xs text-muted" title={source.feed_url}>{source.feed_url}</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-xs text-muted"><span>{source.category}</span>{tab===0?<><span>{source.enabled?'已启用':'已停用'}</span>{!modified.has(source.id)&&source.enabled?<span className={state?.status==='error'||last?.status==='error'?'text-red-800':'text-brand'}>{state?.status==='error'||last?.status==='error'?'采集异常':state?.status==='active'||last?.status==='ok'?'采集正常':stateStatus==='ready'?'等待采集':'状态未知'}</span>:null}{last?.article_count!==undefined?<span>{last.article_count} 篇已发布</span>:null}{duplicates.has(source.feed_url)?<span className="text-red-800">地址重复</span>:null}</>:tab===1?<><span className="text-brand">验证通过 · {formatDate(source.verified_at)}</span>{source.discovered_from&&webUrl(source.discovered_from)?<a className="underline underline-offset-4" href={source.discovered_from} target="_blank" rel="noopener noreferrer">发现出处</a>:null}</>:<><span>失败 {state?.failures ?? 0} 次</span><span>归档于 {formatDate(state?.archived_at)}</span><span>最近复查 {formatDate(state?.last_checked_at)}</span></>}</div>{tab===2?<p className="mt-3 break-words text-xs leading-5 text-red-800">{state?.last_error || '持续采集失败'}</p>:null}</div><div className="flex shrink-0 flex-col gap-2">{tab===1?<Button className="btn" onClick={()=>openEditor(source)}>加入草稿</Button>:<><Button className="btn" aria-label={`编辑 ${source.title} (${source.id})`} onClick={()=>openEditor(source)}>编辑</Button>{tab===2?<Button className="btn" onClick={()=>restore(source)}>请求复查</Button>:null}</>}</div></article>;}):<div className="py-16 text-center"><h2 className="font-semibold">{query||category!=='all'||filter!=='all'?'没有匹配的来源':tab===1?discoveryStatus==='ready'?'暂时没有待确认来源':'待确认来源数量未知':tab===2?stateStatus==='ready'?'暂无归档来源':'归档状态未知':'还没有来源'}</h2><p className="mt-2 text-sm text-muted">{tab===1?'候选会在定时发现并验证后出现，也可通过 OPML 导入。':tab===2?'持续异常的来源会自动归档，短暂失败仍可在公共订阅中查看。':'调整筛选条件，或添加一个 RSS 地址。'}</p></div>}</div>
  <nav aria-label="来源分页" className="flex items-center justify-between py-6"><Button className="btn" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>上一页</Button><span className="text-xs tabular-nums text-muted">第 {currentPage} / {pages} 页</span><Button className="btn" disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}>下一页</Button></nav></>;
  return <><a href="#directory" className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-50 focus:bg-panel focus:p-4">跳到来源列表</a><Shell current="sources"/>
  <main className="mx-auto max-w-7xl px-4 py-8 sm:px-8 sm:py-10"><div className="flex flex-wrap items-start justify-between gap-5"><div><h1 className="text-3xl font-semibold tracking-tight">订阅源</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted">筛选可靠的信息入口。发现新来源，维护参与公共采集的订阅。</p></div><div className="flex gap-2"><Menu><MenuButton className="btn" disabled={!config}>导入与导出</MenuButton><MenuItems className="absolute right-4 z-30 mt-2 min-w-44 rounded-lg border border-line bg-panel p-1 shadow-lg sm:right-8">{[['导入 OPML',()=>importInput.current?.click()],['导出 OPML',()=>download('subscriptions.opml',exportOpml(authored),'text/xml')],['下载 JSON',()=>{if(stale){setReview(true);return;}download('sources.json',configText(),'application/json');}]] .map(([label,action])=><MenuItem key={label as string}><Button className="block min-h-11 w-full rounded px-3 py-2 text-left text-sm data-focus:bg-soft" onClick={action as ()=>void}>{label as string}</Button></MenuItem>)}</MenuItems></Menu><Button className="btn btn-primary" disabled={!config} onClick={()=>openEditor(emptySource())}>添加来源</Button></div></div>
  <input ref={importInput} className="hidden" aria-label="导入 OPML 文件" type="file" accept=".opml,.xml" onChange={event=>void importFile(event.target.files?.[0])}/>
  <p className="mt-5 text-sm text-muted">采集状态与更新时间可在 <a className="text-brand underline underline-offset-4" href="./sync.html">同步记录</a> 中查看。</p><section className={`draft-status my-7 flex flex-wrap items-center justify-between gap-4 border-y border-line py-4 ${diff.length?'has-changes':''}`} aria-label="草稿状态"><div><strong className="text-sm">{loading?'正在加载':diff.length?`${diff.length} 个来源有待发布改动`:'配置与发布版本一致'}</strong><p role="status" aria-live="polite" className="mt-1 text-xs leading-5 text-muted">{message}</p></div><Button className="btn" disabled={!config} onClick={()=>setReview(true)}>检查改动与提交</Button></section>
  {stale?<div className="mb-6 rounded-md bg-amber-50 p-4 text-sm leading-6 text-amber-900"><strong>远程配置已更新，或草稿来自旧版编辑器。</strong><p>提交前先合并最新配置；同一字段冲突时保留本机改动，请在改动清单中核对。</p>{conflicts.length?<div className="mt-3 space-y-3">{conflicts.map((item,index)=><div key={`${item.id}-${index}`} className="break-words text-sm"><strong>{item.title} · {item.key==='source'?'来源存在状态':fieldLabels[item.key]}</strong><p>远程：{fieldValue(item.remote)}</p><p>本机：{fieldValue(item.local)}</p></div>)}<label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={conflictReviewed} onChange={event=>setConflictReviewed(event.target.checked)}/>已核对冲突，合并时采用以上本机值</label></div>:null}<Button className="btn mt-3" disabled={!!conflicts.length&&!conflictReviewed} onClick={()=>{if(!config||!published||!base)return;const merged=rebaseDraft(base,config,published);setBase(published);setStale(false);setConfig(merged);try{localStorage.setItem(draftKey,JSON.stringify({version:2,base:published,config:merged}));}catch{}setMessage('已合并远程配置并保留本机改动，请检查改动清单。');}}>合并远程更新</Button></div>:null}
  {loadError?<section className="py-12 text-center"><h2 className="text-lg font-semibold">暂时无法加载来源</h2><p className="my-3 text-muted">保存在浏览器中的草稿不会被删除。</p><Button className="btn" onClick={()=>location.reload()}>重新加载</Button></section>:<section id="directory" aria-label="来源目录"><TabGroup selectedIndex={tab} onChange={value=>{setTab(value);setProvider('');setPage(1);setSelected(new Set());setCategory('all');setFilter('all');}}><TabList className="grid grid-cols-2 gap-1 border-b border-line sm:flex sm:overflow-x-auto">{[`公共订阅 ${active.length}`,`发现新源 ${discoveryStatus==='ready'?candidates.length:'—'}`,`异常归档 ${stateStatus==='ready'?archive.length:'—'}`,`发现出处 ${directoryStatus==='ready'?new Set(directories.map(item=>item.page)).size:'—'}`].map(title=><Tab key={title} className="min-h-12 shrink-0 border-b-2 border-transparent px-4 py-3 text-sm text-muted data-selected:border-brand data-selected:font-semibold data-selected:text-ink data-hover:bg-soft">{title}</Tab>)}</TabList>
<TabPanels>{[0,1,2,3].map(index=><TabPanel key={index}>{index===3?<>{directoryStatus!=='ready'?<div role="status" className="my-4 text-sm text-muted"><p>{directoryStatus==='loading'?'正在读取发现出处…':'发现出处读取失败，数量未知。'}</p><Button className="btn mt-2" disabled={directoryStatus==='loading'} onClick={()=>void retrySection('directories')}>重试发现出处</Button></div>:null}{discoveryStatus!=='ready'?<div role="status" className="my-4 text-sm text-muted"><p>候选与目录检查状态尚未读取成功，数量未知。</p><Button className="btn mt-2" disabled={discoveryStatus==='loading'} onClick={()=>void retrySection('discovery')}>重试发现状态</Button></div>:null}{directories.length||directoryStatus==='ready'?<Provenance known={discoveryStatus==='ready'} directories={directories} states={discovery.directories??[]} candidates={candidates} onCandidates={page=>{setProvider(page);setTab(1);setQuery('');setCategory('all');setPage(1);}}/>:null}</>:<>{provider&&index===1?<p className="mt-5 text-sm text-muted">当前出处 {provider} <button className="ml-3 text-brand underline" onClick={()=>setProvider('')}>查看全部候选</button></p>:null}{panelContent}</>}</TabPanel>)}</TabPanels></TabGroup></section>}
  <footer className="mt-6 border-t border-line pt-6 text-xs leading-6 text-muted">来源配置提交后才会改变公共采集。手机关注偏好独立保存。<a className="ml-3 underline underline-offset-4" href="./sync.html" target="_blank" rel="noopener noreferrer">查看同步记录</a></footer></main>
  <Modal open={!!editing} title={authored.some(source=>source.id===editing?.id)?'编辑来源':'添加来源'} description="保存到本机草稿后，再检查并提交配置。" onClose={closeEditor}>{editing?<form onSubmit={commitEditor} className="mt-6 space-y-5">{(['title','feed_url','category','description'] as const).map((key,index)=><Field key={key}><Label className="mb-2 block text-sm font-medium">{['名称','RSS 地址','分类','简介'][index]}</Label>{key==='description'?<Textarea className="field min-h-24 resize-y" value={editing[key]} onChange={event=>setEditing({...editing,[key]:event.target.value})}/>:<Input autoFocus={key==='title'} className="field" required type={key==='feed_url'?'url':'text'} value={editing[key]} onChange={event=>setEditing({...editing,[key]:event.target.value})}/>}</Field>)}<Field className="flex items-center justify-between gap-4"><div><Label className="text-sm font-medium">参与公共采集</Label><p className="mt-1 text-xs text-muted">提交发布后影响所有使用公共目录的客户端；停用会停止日常采集。</p></div><Switch checked={editing.enabled} onChange={enabled=>setEditing({...editing,enabled})} className="group inline-flex h-11 w-16 shrink-0 items-center rounded-full bg-muted p-1 data-checked:bg-brand"><span className="size-5 rounded-full bg-white transition-transform group-data-checked:translate-x-8"/></Switch></Field>{archived(editing,health[editing.id])?<p className="rounded-md bg-soft p-3 text-sm text-brand">此来源已归档。修改 RSS 地址，或在归档列表请求复查，通过后恢复采集。</p>:null}{editError?<p role="alert" className="text-sm text-red-800">{editError}</p>:null}<div className="flex flex-wrap gap-2 border-t border-line pt-5"><Button type="submit" className="btn btn-primary">保存到草稿</Button><Button className="btn" onClick={closeEditor}>取消</Button>{authored.some(source=>source.id===editing.id)?<Button className="btn ml-auto text-red-800" onClick={()=>setConfirmAction({title:`删除「${editing.title}」？`,description:'此操作先修改本机草稿，提交发布后才会移除公共来源。',run:()=>{updateSources(authored.filter(source=>source.id!==editing.id));setEditing(undefined);}})}>删除来源</Button>:null}</div></form>:null}</Modal>
  <Modal wide open={review} title="检查改动与提交" description="核对改动后，前往 GitHub 确认一次。CI 自动校验、应用配置并采集发布。" onClose={()=>setReview(false)}><details open className="mt-5 border-y border-line py-4"><summary className="min-h-11 cursor-pointer py-3 text-sm font-semibold">1 · 核对公共订阅改动（{diff.length} 个来源）</summary><div>{diff.length?<ul className="space-y-2 text-sm">{diff.map(item=><li key={item.id} className="break-words"><strong><span className="mr-3 text-brand">{item.kind}</span>{item.title}</strong><dl className="mt-2 space-y-2 text-xs leading-6 text-muted">{item.fields.map(field=><div key={field.key}><dt className="font-medium text-ink">{fieldLabels[field.key]}</dt><dd>原值：{fieldValue(field.before)}</dd><dd>新值：{fieldValue(field.after)}</dd></div>)}</dl></li>)}</ul>:<p className="text-sm text-muted">当前没有待发布改动。</p>}</div></details>{stale?<p className="mt-4 text-sm text-red-800">远程配置有更新，请先关闭此窗口并合并远程更新，再导出草稿。</p>:null}{published&&config&&diff.length?<Publisher base={published} draft={config} onPublished={acceptPublished} blocked={stale||!diff.length||!!duplicates.size}/>:null}<details className="mt-6 border-t border-line pt-5"><summary className="min-h-11 cursor-pointer text-sm font-semibold">手动提交与备份</summary><div className="flex flex-wrap gap-2"><Button className="btn" disabled={stale||!config} onClick={async()=>{try{await navigator.clipboard.writeText(configText());setMessage('配置已复制，请在 GitHub 粘贴并提交到新分支。');}catch{setMessage('复制失败，请下载 JSON 后手动粘贴。');}}}>复制配置</Button><Button className="btn" disabled={stale||!published} onClick={()=>{if(!published)return;const repo=published.repository;window.open(`https://github.com/${encodeURIComponent(repo.owner)}/${encodeURIComponent(repo.name)}/edit/${encodeURIComponent(repo.branch)}/${repo.path.split('/').map(encodeURIComponent).join('/')}`,'_blank','noopener,noreferrer');}}>打开 GitHub 编辑</Button><Button className="btn" disabled={stale||!config} onClick={()=>download('sources.json',configText(),'application/json')}>下载 JSON</Button><Button className="btn text-red-800" disabled={!diff.length} onClick={reset}>丢弃草稿</Button></div><p className="mt-4 text-xs text-muted">复制与下载不会提交或发布配置。</p></details></Modal>
  <Modal open={!!confirmAction} title={confirmAction?.title ?? ''} description={confirmAction?.description} onClose={()=>setConfirmAction(undefined)}><div className="mt-6 flex justify-end gap-2"><Button className="btn" onClick={()=>setConfirmAction(undefined)}>取消操作</Button><Button className="btn btn-primary" onClick={()=>{confirmAction?.run();setConfirmAction(undefined);}}>确认</Button></div></Modal>
  </>;
}
createRoot(document.getElementById('root')!).render(<Manager/>);
