import {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Shell} from './shell.tsx';
import {readJson,type Source} from './catalog.ts';
import {type Health} from './source-manager-model.ts';
type Run={generated_at:string;finished_at?:string;duration_seconds:number;checked:number;succeeded:number;failed:number;archived:number;article_count:number;workflow_run_id?:string};
const stamp=(value?:string)=>value?new Intl.DateTimeFormat('zh-CN',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Shanghai'}).format(new Date(value)):'暂无记录';
const actions='https://github.com/chcaty/garss-next/actions';
function Sync(){
 const [data,setData]=useState<{generated:string;feeds:Source[];states:Record<string,Health>;runs:Run[];discovery:{last_attempt_at?:string;candidates?:unknown[];directory_errors?:{directory:string;error:string}[]}}>();
 const [error,setError]=useState(false);const [filter,setFilter]=useState('all');const [query,setQuery]=useState('');const [page,setPage]=useState(1);const [notice,setNotice]=useState('');
 useEffect(()=>{let alive=true;void (async()=>{try{const values=await Promise.allSettled([readJson<{generated_at:string}>('./api/v1/meta.json'),readJson<{feeds:Source[]}>('./api/v1/feeds.json'),readJson<{sources:Record<string,Health>}>('./api/v1/source-state.json'),readJson<{runs:Run[]}>('./api/v1/sync.json'),readJson<NonNullable<typeof data>['discovery']>('./api/v1/source-discovery.json')]);if(!alive)return;const [meta,feeds,states,runs,discovery]=values;if(meta.status!=='fulfilled'||feeds.status!=='fulfilled')throw Error();setData({generated:meta.value.generated_at,feeds:feeds.value.feeds,states:states.status==='fulfilled'?states.value.sources:{},runs:runs.status==='fulfilled'?runs.value.runs:[],discovery:discovery.status==='fulfilled'?discovery.value:{}});if(states.status==='rejected'||discovery.status==='rejected')setNotice('部分来源或发现状态暂时无法读取，刷新页面可重试。');}catch{if(alive)setError(true);}})();return()=>{alive=false;};},[]);
 const status=(source:Source)=>data?.states[source.id]?.status==='archived'?'archived':!source.enabled?'disabled':source.status==='error'||data?.states[source.id]?.status==='error'?'error':source.status==='ok'?'ok':'pending';
 const names:Record<string,string>={ok:'采集正常',error:'采集异常',archived:'已归档',disabled:'已停用',pending:'等待采集'};
 const entries=data?.feeds.filter(source=>(filter==='all'||status(source)===filter)&&`${source.title} ${source.category} ${source.feed_url}`.toLowerCase().includes(query.trim().toLowerCase()))??[];
 const pages=Math.max(1,Math.ceil(entries.length/20));const current=Math.min(page,pages);
 const latest=data?.runs[0];
 return <><Shell current="sync"/><main className="mx-auto max-w-7xl px-4 py-8 sm:px-8 sm:py-10"><div className="page-intro"><div><h1 className="page-title">同步记录</h1><p className="mt-3 text-sm leading-6 text-muted">确认信息何时更新，查看每个来源的采集情况。</p></div><div className="flex flex-wrap gap-2"><button className="btn" onClick={()=>location.reload()}>刷新状态</button><a className="btn" href={actions} target="_blank" rel="noopener noreferrer">采集任务与日志</a></div></div>
 {error?<section role="alert" className="py-12"><h2 className="text-xl font-semibold">同步记录暂时无法加载</h2><p className="mt-3 text-muted">刷新页面重试，也可以打开 GitHub 采集日志。</p></section>:!data?<p role="status" className="py-12 text-muted">正在读取最近同步…</p>:<>
 <section aria-label="最近同步" className="border-y border-line py-6"><div className="flex flex-wrap items-center justify-between gap-5"><div><h2 className="text-lg font-semibold">最近已发布采集</h2><p className="mt-2 text-sm text-muted">北京时间 {stamp(data.generated)}</p></div><p className="text-sm text-muted">正常 <strong className="text-ink">{data.feeds.filter(source=>status(source)==='ok').length}</strong> · 异常 <strong className="text-red-800">{data.feeds.filter(source=>status(source)==='error').length}</strong> · 归档 <strong className="text-ink">{data.feeds.filter(source=>status(source)==='archived').length}</strong></p></div><p className="mt-4 text-xs leading-6 text-muted">每天北京时间 06:00、13:00、17:00、22:00 计划采集，实际启动时间可能受 GitHub 排队影响。{latest?`本次检查 ${latest.checked} 个来源，耗时 ${latest.duration_seconds} 秒，发布 ${latest.article_count} 篇去重文章。`:''}</p><p className="mt-1 text-xs leading-6 text-muted">此处展示已发布的数据；运行中或未发布的失败任务，请查看采集日志。</p></section>
 {notice?<p role="status" className="mt-4 text-sm text-muted">{notice}</p>:null}
 <section className="mt-8" aria-labelledby="source-status-title"><div className="flex flex-wrap items-center justify-between gap-4"><h2 id="source-status-title" className="text-xl font-semibold">来源采集情况</h2><a className="text-sm text-brand underline underline-offset-4" href="./sources.html">维护订阅源</a></div><div className="my-5 grid gap-3 sm:grid-cols-2"><label className="text-xs text-muted">查找来源<input className="field mt-2" type="search" value={query} placeholder="名称、分类或 RSS 地址" onChange={event=>{setQuery(event.target.value);setPage(1);}}/></label><label className="text-xs text-muted">采集状态<select aria-label="采集状态" className="field mt-2" value={filter} onChange={event=>{setFilter(event.target.value);setPage(1);}}>{[['all','全部状态'],...Object.entries(names)].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div><p className="mb-3 text-xs text-muted">{entries.length} 个来源</p><div className="border-t border-line">{entries.slice((current-1)*20,current*20).map(source=>{const state=data.states[source.id];const condition=status(source);return <article className="border-b border-line py-4" key={source.id}><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-semibold">{source.title}</h3><span className={condition==='error'?'text-xs text-red-800':'text-xs text-muted'}>{names[condition]}</span></div><p className="mt-2 text-xs leading-6 text-muted">{source.category} · {source.article_count??0} 篇保留文章 · 最近检查 {stamp(state?.last_checked_at)}</p>{state?.last_error?<p className="mt-2 break-words text-xs leading-6 text-red-800">{state.last_error}</p>:null}{state?.last_success_at?<p className="mt-1 text-xs text-muted">最近成功 {stamp(state.last_success_at)}</p>:null}</article>;})}{!entries.length?<p className="py-10 text-sm text-muted">没有匹配的来源，调整关键词或状态筛选。</p>:null}</div><nav aria-label="状态列表分页" className="my-5 flex items-center justify-between"><button className="btn" disabled={current===1} onClick={()=>setPage(current-1)}>上一页</button><span className="text-xs text-muted">第 {current} / {pages} 页</span><button className="btn" disabled={current===pages} onClick={()=>setPage(current+1)}>下一页</button></nav></section>
 <section className="mt-10 border-t border-line pt-6"><h2 className="text-xl font-semibold">采集批次</h2><p className="mt-2 text-xs leading-6 text-muted">保留最近 30 次已发布记录，成功数包含正常但没有新文章的来源。</p>{data.runs.length?<div className="mt-5 divide-y divide-line">{data.runs.map(run=><div key={run.generated_at} className="flex flex-wrap items-center justify-between gap-3 py-4 text-sm"><div><p className="font-medium">{stamp(run.generated_at)}</p><p className="mt-2 text-xs text-muted">正常 {run.succeeded} / 异常 {run.failed} · {run.article_count} 篇文章 · {run.duration_seconds} 秒</p></div>{/^\d+$/.test(run.workflow_run_id??'')?<a className="btn" href={`${actions}/runs/${run.workflow_run_id}`} target="_blank" rel="noopener noreferrer">本次日志</a>:null}</div>)}</div>:<p className="mt-5 text-sm text-muted">历史记录从新版采集发布后开始积累。</p>}</section>
 <section className="mt-10 border-t border-line py-6"><h2 className="text-xl font-semibold">新来源发现</h2><a className="mt-3 inline-block text-sm text-brand underline" href="./sources.html#provenance">查看发现出处</a><p className="mt-3 text-sm leading-7 text-muted">最近发现检查 {stamp(data.discovery.last_attempt_at)} · 待确认 {data.discovery.candidates?.length??0} 个 · 目录异常 {data.discovery.directory_errors?.length??0} 个</p><p className="mt-2 text-xs leading-6 text-muted">外部目录每 7 天检查一次；只有验证通过的候选才会进入订阅源页面，加入草稿，在 GitHub 确认并通过校验后参与采集。</p>{data.discovery.directory_errors?.map(item=><p key={item.directory} className="mt-2 break-words text-xs text-red-800">{item.directory}：{item.error}</p>)}</section></>}
 </main></>;
}
createRoot(document.getElementById('root')!).render(<Sync/>);
